#!/bin/bash

set -e

echo '--> Installing Dependencies'
go get github.com/mitchellh/gox
go get

echo '--> Building'
go build

echo '--> Testing'
go test -v

echo '--> Cross compiling'
gox -osarch="darwin/amd64 linux/386 linux/amd64 linux/arm" -output="out/{{.Dir}}_{{.OS}}_{{.Arch}}"